import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Webcam from "react-webcam";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen add-bg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl min-h-screen flex flex-col items-center justify-center lg:justify-around mx-auto">
        <div className="flex items-center">
          <Image src="/mirror.png" height={150} width={150} alt="mirror" />
          <h1 className="text-white font-bold text-5xl">Mraya</h1>
          <Image src="/mirror.png" height={150} width={150} alt="mirror" />
        </div>
        <Webcam className="min-w-full md:min-w-[500px] md:w-1/2 lg:w-[70%] rounded-xl mb-10" />
      </div>
    </div>
  );
};

export default Home;
