import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Webcam from 'react-webcam'

const Home: NextPage = () => {
  return (
    <div className="min-h-screen bg-black flex flex-col items-center justify-center lg:justify-around">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-white text-5xl">Mraya</h1>
      <Webcam className="w-full md:w-1/2 lg:w-1/3 rounded-xl"/>
      
    </div>
  )
}

export default Home
